project:
  type: website
  output-dir: docs

website:
  title: "Mikaela K. Nishida"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: Nishida_CV_031425.pdf
        text: CV

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

